# Generated by Django 5.1 on 2024-08-24 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Torb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_ID', models.IntegerField(default=0)),
                ('generation', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('health', models.IntegerField(default=10)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.colony')),
            ],
        ),
    ]
