# Generated by Django 5.1 on 2024-08-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0003_colony_name_colony_num_torbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='num_torbs',
        ),
        migrations.AddField(
            model_name='torb',
            name='name',
            field=models.CharField(default='Nonam', max_length=16),
        ),
    ]
