# Generated by Django 5.1 on 2024-08-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0005_game_colony_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='game',
        ),
    ]
