# Generated by Django 5.1 on 2024-08-24 03:39

import django.db.models.deletion
from django.db import migrations, models

def create_default_game(apps, schema_editor):
    Game = apps.get_model('main_game', 'Game')
    default_game = Game.objects.create(starting_torbs=4)
    return default_game.id

def set_default_game(apps, schema_editor):
    Colony = apps.get_model('main_game', 'Colony')
    Game = apps.get_model('main_game', 'Game')
    default_game = Game.objects.first()  # Get the first or create the Game object
    Colony.objects.all().update(game=default_game)

class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0006_remove_colony_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='game',
            field=models.ForeignKey(to='main_game.Game', null=True, on_delete=models.CASCADE),
        ),
    ]
