# Generated by Django 5.1 on 2024-08-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0007_colony_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
