# Generated by Django 5.1 on 2024-08-24 18:59

import django.db.models.deletion
import main_game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0008_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_gene_min', models.IntegerField(default=1)),
                ('random_gene_max', models.IntegerField(default=10)),
                ('mutation_chance', models.FloatField(default=0.1)),
                ('mutation_dev', models.FloatField(default=0.15)),
                ('alleles_per_gene', models.IntegerField(default=2)),
                ('gene_list', models.JSONField(default=main_game.models.evolution_engine.default_gene_list)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.game')),
            ],
        ),
    ]
