# Generated by Django 5.1 on 2024-08-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0009_evolutionengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='torb',
            name='action',
            field=models.CharField(choices=[('gathering', 'gathering'), ('breeding', 'breeding'), ('combatting', 'combatting'), ('training', 'training'), ('resting', 'resting')], default='gathering', max_length=32),
        ),
        migrations.AddField(
            model_name='torb',
            name='action_breeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torb',
            name='action_deploying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torb',
            name='action_growing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torb',
            name='action_resting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torb',
            name='action_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torb',
            name='fertile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='torb',
            name='starving',
            field=models.BooleanField(default=False),
        ),
    ]
