# Generated by Django 5.1 on 2024-08-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0010_torb_action_torb_action_breeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='evolution_engine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_instance', to='main_game.evolutionengine'),
        ),
        migrations.AlterField(
            model_name='evolutionengine',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_engine_instance', to='main_game.game'),
        ),
    ]
