# Generated by Django 5.1 on 2024-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0011_game_evolution_engine_alter_evolutionengine_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torb',
            name='action_breeding',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='action_deploying',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='action_growing',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='action_resting',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='action_training',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='health',
        ),
        migrations.AddField(
            model_name='torb',
            name='agility',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='torb',
            name='hp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='torb',
            name='max_hp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='torb',
            name='strength',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='torb',
            name='sturdiness',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='torb',
            name='vitality',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evolutionengine',
            name='gene_list',
            field=models.JSONField(default=0),
        ),
    ]
