# Generated by Django 5.1 on 2024-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0012_remove_torb_action_breeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionengine',
            name='gene_list',
            field=models.JSONField(default=[2]),
        ),
    ]
