# Generated by Django 5.1 on 2024-08-24 21:07

import main_game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0013_alter_evolutionengine_gene_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionengine',
            name='gene_list',
            field=models.JSONField(default=main_game.models.evolution_engine.default_gene_alleles),
        ),
    ]
