# Generated by Django 5.1 on 2024-08-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0015_remove_torb_agility_remove_torb_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torb',
            name='action',
        ),
        migrations.AddField(
            model_name='torb',
            name='agility',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='torb',
            name='strength',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='torb',
            name='sturdiness',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='torb',
            name='vitality',
            field=models.JSONField(default=list),
        ),
    ]
