# Generated by Django 5.1 on 2024-08-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0016_remove_torb_action_torb_agility_torb_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torb',
            name='genes',
            field=models.JSONField(default=dict),
        ),
    ]
