# Generated by Django 5.1 on 2024-08-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0018_torb_action_torb_action_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='food',
            field=models.IntegerField(default=5),
        ),
    ]
