# Generated by Django 5.1 on 2024-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0019_colony_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
