# Generated by Django 5.1 on 2024-08-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0020_colony_ready'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
