# Generated by Django 5.1 on 2024-08-25 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0021_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text_type', models.CharField(default='default', max_length=32)),
                ('story_text', models.CharField(default='N/A', max_length=1028)),
                ('timestamp', models.DateField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.colony')),
            ],
        ),
    ]
