# Generated by Django 5.1 on 2024-08-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0023_alter_storytext_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torb',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='sturdiness',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='vitality',
        ),
    ]
