# Generated by Django 5.1 on 2024-08-26 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0024_remove_torb_agility_remove_torb_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='gather_rate',
            field=models.FloatField(default=1.7),
        ),
        migrations.AddField(
            model_name='colony',
            name='rest_heal_flat',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='colony',
            name='rest_heal_perc',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='torb',
            name='context_torb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_game.torb'),
        ),
    ]
