# Generated by Django 5.1 on 2024-08-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0026_game_round_number_alter_evolutionengine_gene_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torb',
            name='growing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='torb',
            name='action',
            field=models.CharField(choices=[('gathering', 'gathering'), ('breeding', 'breeding'), ('combatting', 'combatting'), ('training', 'training'), ('resting', 'resting'), ('growing', 'growing')], default='gathering', max_length=32),
        ),
    ]
