# Generated by Django 5.1 on 2024-08-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0027_torb_growing_alter_torb_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='discovered_colonies',
            field=models.ManyToManyField(related_name='discoverers', to='main_game.colony'),
        ),
        migrations.AddField(
            model_name='torb',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='torb',
            name='action',
            field=models.CharField(choices=[('gathering', 'gathering'), ('breeding', 'breeding'), ('soldiering', 'soldiering'), ('training', 'training'), ('resting', 'resting'), ('growing', 'growing')], default='gathering', max_length=32),
        ),
    ]
