# Generated by Django 5.1 on 2024-08-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0028_colony_discovered_colonies_torb_trained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='discovered_colonies',
            field=models.ManyToManyField(null=True, related_name='discoverers', to='main_game.colony'),
        ),
    ]
