# Generated by Django 5.1 on 2024-08-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0029_alter_colony_discovered_colonies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='discovered_colonies',
            field=models.ManyToManyField(blank=True, null=True, related_name='discoverers', to='main_game.colony'),
        ),
    ]
