# Generated by Django 5.1 on 2024-08-31 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0031_alter_colony_discovered_colonies'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='attack_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacking_colonies', to='main_game.colony'),
        ),
        migrations.AddField(
            model_name='colony',
            name='scout_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_colonies', to='main_game.colony'),
        ),
    ]
