# Generated by Django 5.1 on 2024-09-15 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0034_alter_colony_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colony', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='army_instance', to='main_game.colony')),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='army',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colony_army', to='main_game.army'),
        ),
        migrations.AddField(
            model_name='torb',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_game.army'),
        ),
        migrations.CreateModel(
            name='ArmyTorb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_alleles', models.JSONField(default=dict)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army_torbs', to='main_game.army')),
                ('torb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.torb')),
            ],
        ),
    ]
