# Generated by Django 5.1 on 2024-10-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0035_army_colony_army_torb_army_armytorb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='evolution_engine',
        ),
        migrations.AddField(
            model_name='army',
            name='attack_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacking_armies', to='main_game.colony'),
        ),
        migrations.AddField(
            model_name='army',
            name='scout_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_armies', to='main_game.colony'),
        ),
        migrations.AlterField(
            model_name='torb',
            name='action_desc',
            field=models.CharField(default='🌾 Gathering', max_length=256),
        ),
    ]
