# Generated by Django 5.1 on 2024-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0036_remove_game_evolution_engine_army_attack_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='attack_target',
        ),
        migrations.RemoveField(
            model_name='colony',
            name='scout_target',
        ),
        migrations.AddField(
            model_name='army',
            name='morale',
            field=models.IntegerField(default=100),
        ),
    ]
