# Generated by Django 5.1 on 2024-10-13 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0037_remove_colony_attack_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armytorb',
            name='torb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army_torb', to='main_game.torb'),
        ),
    ]
