# Generated by Django 5.1 on 2024-10-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0040_alter_game_allowed_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
