# Generated by Django 5.1 on 2024-10-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0041_game_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_colonies_per_player',
            field=models.IntegerField(default=1),
        ),
    ]
