# Generated by Django 5.1 on 2024-10-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0043_storytext_game_round_storytext_is_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytext',
            name='is_new',
        ),
    ]
