# Generated by Django 5.1 on 2025-02-02 19:34

import django.db.models.deletion
from django.db import migrations, models
import polymorphic


def forwards_func(apps, schema_editor):
    Player = apps.get_model("main_game", "Player")
    AIPlayer = apps.get_model("main_game", "AIPlayer")
    ContentType = apps.get_model("contenttypes", "ContentType")
    
    player_ct = ContentType.objects.get_for_model(Player)
    aiplayer_ct = ContentType.objects.get_for_model(AIPlayer)
    
    Player.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=player_ct)
    AIPlayer.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=aiplayer_ct)
    
    # Ensure AIPlayer instances have the correct polymorphic_ctype
    for aiplayer in AIPlayer.objects.all():
        aiplayer.polymorphic_ctype = aiplayer_ct
        aiplayer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main_game', '0045_player_aiplayer_alter_colony_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiplayer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='player',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
