# Generated by Django 5.1 on 2025-02-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0046_alter_aiplayer_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torb',
            name='colony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torbs', to='main_game.colony'),
        ),
    ]
