# Generated by Django 5.1 on 2025-02-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0047_alter_torb_colony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colonies', to='main_game.player'),
        ),
    ]
