# Generated by Django 5.1 on 2025-02-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0048_alter_colony_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='science',
            field=models.IntegerField(default=0),
        ),
    ]
