# Generated by Django 5.1 on 2025-02-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0049_colony_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='mutagen',
            field=models.IntegerField(default=0),
        ),
    ]
