# Generated by Django 5.1 on 2025-02-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0050_colony_mutagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('research_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='colony',
            name='science',
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_points', models.IntegerField(default=0)),
                ('discoveries', models.ManyToManyField(blank=True, related_name='science_labs', to='main_game.discovery')),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='science_lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colony_science_lab', to='main_game.science'),
        ),
    ]
