# Generated by Django 5.1 on 2025-02-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0051_discovery_remove_colony_science_science_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_points', models.IntegerField(default=0)),
                ('discoveries', models.ManyToManyField(blank=True, related_name='labs', to='main_game.discovery')),
            ],
        ),
        migrations.AlterField(
            model_name='colony',
            name='science_lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colony_lab', to='main_game.lab'),
        ),
        migrations.DeleteModel(
            name='Science',
        ),
    ]
