# Generated by Django 5.1 on 2025-02-07 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0052_lab_alter_colony_science_lab_delete_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='science_lab',
        ),
        migrations.AddField(
            model_name='colony',
            name='lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colony', to='main_game.lab'),
        ),
    ]
