# Generated by Django 5.1 on 2025-03-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0053_remove_colony_science_lab_colony_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='lab',
        ),
        migrations.AddField(
            model_name='lab',
            name='colony',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='main_game.colony'),
        ),
    ]
