# Generated by Django 5.1 on 2025-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0054_remove_colony_lab_lab_colony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='mutagen',
        ),
        migrations.AddField(
            model_name='lab',
            name='mutagen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
