# Generated by Django 5.1 on 2026-06-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0055_remove_colony_mutagen_lab_mutagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torb',
            name='action',
            field=models.CharField(choices=[('gathering', 'gathering'), ('breeding', 'breeding'), ('soldiering', 'soldiering'), ('training', 'training'), ('resting', 'resting'), ('growing', 'growing'), ('researching', 'researching')], default='gathering', max_length=32),
        ),
    ]
