# Generated by Django 5.1 on 2026-06-20 20:10

import django.db.models.deletion
from django.db import migrations, models


def repair_legacy_data(apps, schema_editor):
    Game = apps.get_model("main_game", "Game")
    Player = apps.get_model("main_game", "Player")
    Colony = apps.get_model("main_game", "Colony")
    EvolutionEngine = apps.get_model("main_game", "EvolutionEngine")
    Army = apps.get_model("main_game", "Army")
    ArmyTorb = apps.get_model("main_game", "ArmyTorb")
    Lab = apps.get_model("main_game", "Lab")
    Torb = apps.get_model("main_game", "Torb")
    Discovery = apps.get_model("main_game", "Discovery")

    orphan_game = None
    if Colony.objects.filter(game__isnull=True).exists():
        orphan_game = Game.objects.create(description="Recovered legacy game", starting_torbs=0)
        EvolutionEngine.objects.create(game=orphan_game)
        Colony.objects.filter(game__isnull=True).update(game=orphan_game)
    orphan_player = None
    if Colony.objects.filter(player__isnull=True).exists():
        orphan_player = Player.objects.create(name="Recovered legacy owner")
        Colony.objects.filter(player__isnull=True).update(player=orphan_player)

    Lab.objects.filter(colony__isnull=True).delete()
    Lab.objects.filter(mutagen__isnull=True).update(mutagen=0)
    Lab.objects.filter(science_points__lt=0).update(science_points=0)
    Discovery.objects.filter(research_cost__lt=0).update(research_cost=0)
    Army.objects.filter(morale__lt=0).update(morale=0)
    Army.objects.filter(morale__gt=100).update(morale=100)
    Colony.objects.filter(food__lt=0).update(food=0)

    for game in Game.objects.all():
        EvolutionEngine.objects.get_or_create(game=game)
        seen_names = set()
        for colony in Colony.objects.filter(game=game).order_by("pk"):
            base = colony.name
            if colony.name in seen_names:
                colony.name = f"{base}-{colony.pk}"[:64]
                colony.save(update_fields=["name"] )
            seen_names.add(colony.name)
    for colony in Colony.objects.all():
        Army.objects.get_or_create(colony=colony)
        Lab.objects.get_or_create(colony=colony)
        seen_ids = set()
        next_id = 1
        for torb in Torb.objects.filter(colony=colony).order_by("pk"):
            torb.max_hp = max(torb.max_hp, 0)
            torb.hp = min(max(torb.hp, 0), torb.max_hp)
            if torb.private_ID in seen_ids:
                while next_id in seen_ids:
                    next_id += 1
                torb.private_ID = next_id
            seen_ids.add(torb.private_ID)
            torb.save(update_fields=["private_ID", "hp", "max_hp"] )
    seen_torbs = set()
    for membership in ArmyTorb.objects.order_by("pk"):
        if membership.torb_id in seen_torbs:
            membership.delete()
        else:
            seen_torbs.add(membership.torb_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0056_alter_torb_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='army',
        ),
        migrations.RemoveField(
            model_name='torb',
            name='army',
        ),
        migrations.AddField(
            model_name='game',
            name='round_seed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='round_status',
            field=models.CharField(choices=[('open', 'Open'), ('resolving', 'Resolving'), ('complete', 'Complete')], default='open', max_length=16),
        ),
        migrations.RunPython(repair_legacy_data, noop_reverse),
        migrations.AlterField(
            model_name='colony',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.game'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colonies', to='main_game.player'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='colony',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='main_game.colony'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='mutagen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torb',
            name='action',
            field=models.CharField(choices=[('gathering', 'Gathering'), ('breeding', 'Breeding'), ('soldiering', 'Soldiering'), ('training', 'Training'), ('resting', 'Resting'), ('growing', 'Growing'), ('researching', 'Researching'), ('dead', 'Dead')], default='gathering', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='army',
            constraint=models.CheckConstraint(condition=models.Q(('morale__gte', 0), ('morale__lte', 100)), name='army_morale_in_range'),
        ),
        migrations.AddConstraint(
            model_name='armytorb',
            constraint=models.UniqueConstraint(fields=('torb',), name='unique_army_membership_per_torb'),
        ),
        migrations.AddConstraint(
            model_name='colony',
            constraint=models.CheckConstraint(condition=models.Q(('food__gte', 0)), name='colony_food_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='discovery',
            constraint=models.CheckConstraint(condition=models.Q(('research_cost__gte', 0)), name='discovery_research_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.CheckConstraint(condition=models.Q(('science_points__gte', 0)), name='lab_science_points_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.CheckConstraint(condition=models.Q(('mutagen__gte', 0)), name='lab_mutagen_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='torb',
            constraint=models.CheckConstraint(condition=models.Q(('hp__gte', 0), ('max_hp__gte', 0), ('hp__lte', models.F('max_hp'))), name='torb_hp_in_range'),
        ),
        migrations.AddConstraint(
            model_name='torb',
            constraint=models.UniqueConstraint(fields=('colony', 'private_ID'), name='unique_torb_private_id_per_colony'),
        ),
    ]
